# Generated by Django 2.1.15 on 2020-01-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_auto_20181204_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='interlock',
            name='operating_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='interlocklog',
            name='active_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
